---

name: CI

on:
  workflow_call:
    inputs:
      build-ios:
        default: false
        required: false
        type: boolean

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: flutter pub get
      - name: Check code formatting
        run: dart format -o show --set-exit-if-changed .
      - name: Run static analysis
        run: dart analyze --fatal-infos
      - name: Test
        run: flutter test
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          cache: gradle
          distribution: corretto
          java-version: "11"
      - name: Build APK
        run: flutter build apk
      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-release.apk
  build-ios:
    if: inputs.build-ios
    name: Build iOS
    needs:
      - ci
    runs-on: macos-latest
    steps:
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: flutter pub get
      - name: Build iOS app
        run: flutter build ios --no-codesign
      - name: Upload iOS app artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-app
          path: build/ios/iphoneos/Runner.app
