---

name: CI

on:
  workflow_call:
    inputs:
      build-apk:
        default: false
        required: false
        type: boolean
      build-ios:
        default: false
        required: false
        type: boolean
      build-runner:
        default: false
        required: false
        type: boolean
      report:
        default: true
        required: false
        type: boolean

jobs:
  ci:
    name: CI
    permissions:
      actions: read
      checks: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: flutter pub get
      - name: Check code formatting
        run: dart format -o show --set-exit-if-changed .
      - if: inputs.build-runner
        name: Run `build_runner`
        run: dart run build_runner build
      - name: Run static analysis
        run: dart analyze --fatal-infos
      - name: Test
        run: flutter test
      - if: inputs.report
        name: Upload test report artifact
        uses: actions/upload-artifact@v3
        with:
          name: tests
          path: reports/tests.json
      - if: inputs.report
        name: Report test results
        uses: dorny/test-reporter@v1
        with:
          artifact: tests
          name: Tests
          path: reports/tests.json
          reporter: flutter-json
      - if: inputs.build-apk
        name: Set up Java
        uses: actions/setup-java@v3
        with:
          cache: gradle
          distribution: corretto
          java-version: "11"
      - if: inputs.build-apk
        name: Build APK
        run: flutter build apk
      - if: inputs.build-apk
        name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-release.apk
  build-ios:
    if: inputs.build-ios
    name: Build iOS
    needs:
      - ci
    runs-on: macos-latest
    steps:
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: flutter pub get
      - name: Build iOS app
        run: flutter build ios --no-codesign
      - name: Upload iOS app artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-app
          path: build/ios/iphoneos/Runner.app
