---

name: Report test results

on:
  workflow_call:
    inputs:
      flutter:
        default: false
        required: false
        type: boolean

jobs:
  report:
    name: Report test results
    permissions:
      actions: read
      checks: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Report test results
        uses: dorny/test-reporter@v1
        with:
          artifact: tests
          name: Tests
          path: reports/tests.json
          reporter: ${{ inputs.flutter && 'flutter' || 'dart' }}-json
